### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by siddharthg** [siddharthg/org.civicrm.civisocial#10]
Create documentation for the following tasks:-
- [ ] Installing Extension
- [ ] Setting it up
- [ ] Enable Custom Scopes
- [ ] Adding another oauth provider

**Comment by xurizaemon** [comment]
Hi Siddharth! Some other things that would really help people "try the waters" of this extension :smile: 

- [ ] What does it do? What features does this extension add to CiviCRM?
- [ ] What does it look like? Screenshots of the functionality are great to show people how it works.
- [ ] TODO - what are the next steps for people to contribute to this?

**Comment by ngareth** [comment]
Hi @siddharthg @xurizaemon : Does this repo contain all the work that was done on the Extension by @rolencea and @siddharthg ?

**Comment by xurizaemon** [comment]
I believe @rolencea's work is https://github.com/rolencea/org.civicrm.civisocial2

I've asked Aka to document that work also - see rolencea/org.civicrm.civisocial2#1

**Comment by rolencea** [comment]
will do that ASAP

**Comment by ngareth** [comment]
My suggestion, @xurizaemon also merging the two repos into one standard repo can really give new contributors a good feel to project. I think a new issue should be open for it

**Comment by siddharthg** [comment]
Completed via #47
