### ISSUE TITLE
Google+ authentication does not preserve profile ID?

### ISSUE THREAD

**Issue by xurizaemon** [siddharthg/org.civicrm.civisocial#3]
On a test site (Drupal / CiviCRM 4.6 via `civibuild`), I configured Google+ authentication. I was able to navigate to Google and confirm the request for access to profile data, but on return to CiviCRM I saw

> **Sorry but we are not able to provide this at the moment.**
> 
> One of parameters (value: ) is not of the type Integer
> 
> Return to home page.

**Comment by siddharthg** [comment]
I got the same error even after the extension was disabled.

**Comment by rajbdilip** [comment]
@siddharthg Is this still applicable? I think this can be closed.

**Comment by siddharthg** [comment]
Can you test this scenario?

**Comment by rajbdilip** [comment]
@siddharthg There is no such issue on callback handling. After successful authentication, profile ID is saved both in Session and the database.
