### ISSUE TITLE
CiviCRM reports logged in via g+, but doesn't populate default profile fields

### ISSUE THREAD

**Issue by xurizaemon** [siddharthg/org.civicrm.civisocial#4]
CiviCRM 4.6 / Drupal 7 via `civibuild`, viewing the default profile **1**.

![screenshot 2015-08-28 09 48 19](https://cloud.githubusercontent.com/assets/105608/9534068/3a1f61ba-4d6a-11e5-9f94-86217b9ee6e7.png)

Since I'm logged in and CiviCRM is showing Firstname Lastname, I'd expect these details to be populated in the profile form?

**Comment by rajbdilip** [comment]
The latest PR addresses this. #23
