### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dsuguy2007** [siddharthg/org.civicrm.civisocial#53]
After setting everything up and going to civicrm/admin/civisocial/network to click Connect to Facebook and Twitter when I click on connect to Facebook it asks for authorization, I clicked agree, then it asks to be able to manage pages clicked agree, then I get the following error:

Fatal error: Cannot redeclare class OAuthSignatureMethod_HMAC_SHA1 in /www/sites/all/modules/oauth/lib/OAuth.php on line 144

Tried Connecting Twitter but get the same error.

**Comment by rajbdilip** [comment]
@dsuguy2007 Thanks for reporting. We will look into the issue and get back to you as soon as possible.

**Comment by dsuguy2007** [comment]
@rajbdilip Any update on this?

**Comment by siddharthg** [comment]
@dsuguy2007 you are facing this because you already have a OAuth module installed in your drupal setup which uses the same class name. I will try to change the namespace of the OAuth methods and this should fix it.

**Comment by dsuguy2007** [comment]
that fixed it!!!
