### ISSUE TITLE
Validate credentials when saving admin settings screen

### ISSUE THREAD

**Issue by xurizaemon** [siddharthg/org.civicrm.civisocial#6]
It's easy to copy a space before or after the API keys - this can let you save the creds, then find they don't work later.

We could validate API auth when saving the settings screen (and perhaps also trim whitespace from ends), then the admin would have a better chance of catching such mistakes.

**Comment by rajbdilip** [comment]
@siddharthg @xurizaemon Maybe we can we have `Verify Credentials` button or link, clicking which would take the admin to a login page.
