### ISSUE TITLE
Facebook login identifies me as wrong user?

### ISSUE THREAD

**Issue by xurizaemon** [siddharthg/org.civicrm.civisocial#8]
I logged in via Facebook, but when I returned to the CiviCRM site I'd been authenticated as *Dr. Herminia Grant.*

This contact is id=2 in the CiviCRM sample dataset, and does not have an email address.

If FB doesn't return an email, then the extension may be incorrectly matching against the first found contact with no email address.

**Comment by siddharthg** [comment]
The system now creates a new user in case of no email given
Fixed via 24620cdca1bf8c1bb1af3c095f1405ae0b03cdda
